version: '3.8'

services:
  nestjs_prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: nestjs_prod
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - APP_SOCKET_PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
      - /home/ubuntu/backup/BkKey.pem:/app/keys/BkKey.pem
    command: npm run start