version: '3.8'

services:
  nestjs_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    container_name: nestjs_dev
    ports:
      - "3200:3200"
      - "3201:3201"
    environment:
      - NODE_ENV=development
      - APP_SOCKET_PORT=3201
    volumes:
      - .:/app
      - /app/node_modules
      - /home/ubuntu/backup/BkKey.pem:/app/keys/BkKey.pem
    command: npm run start dev